### ISSUE TITLE
Criar endpoint de adicionar animal

### ISSUE THREAD

**Issue by JoseDanielF** [Projeto-Des-SW/betterlife-backend#35]

**Comment by Flayban** [comment]
@Bielfla27 o frontend vai estar enviando um arquivo do tipo json com os seguintes campos:
nome:'',
nomeCientifico:'',
sexo:'',
peso:'',
idade:'',
descricao:'',
observacaoDaEspecie:'',
usuarioId:'',
imagemId:'',
somId:'',
taxonomiaId:'',

E vai enviar esse JSON para a rota api_URL/registerAnimal
